name: C/C++ CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install MSVC Build Tools
      uses: microsoft/setup-msbuild@v1.1
    
    - name: Set up compilers
      env:
        CC: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe
        CXX: C:\Program Files (x86)\Microsoft Visual Studio\2019\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\cl.exe

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.20.5'

    - name: Build
      run: |
        cmake .
        cmake --build .
      
#    - name: Test
#      run: cd build && ctest -C Release
