name: C/C++ CI/CD

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
      
    - name: Install MSVC Build Tools
      uses: microsoft/setup-msbuild@v1.0.5

    - name: Install CMake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.20.5'

    - name: Build
      run: |
        cmake .
        cmake --build .
      
#    - name: Test
#      run: cd build && ctest -C Release
