name: Download Dependencies and Build

on:
  push:
    branches:
      - main  # adjust this to match your main branch name

jobs:
  download_and_build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab the latest version
          repo: go-task/task

      - name: Install Mozilla grcov
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific file extension
          repo: mozilla/grcov
          tag: v0.8.12
          extension: "\\.zip"

      - name: Override dependencies folder
        run: |
          robocopy /mir /e .\dependencies .\MinesweeperSolver\dependencies
          rmdir /s /q .\dependencies

      - name: Build Solver.sln
        working-directory: MinesweeperSolver
        run: msbuild.exe Solver.sln
