name: Download Dependencies and Build

on:
  push:
    branches:
      - main  # adjust this to match your main branch name

jobs:
  download_and_build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install go-task
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab the latest version
          repo: go-task/task

      - name: Install Mozilla grcov
        uses: jaxxstorm/action-install-gh-release@v1.10.0
        with: # Grab a specific file extension
          repo: mozilla/grcov
          tag: v0.8.12
          extension: "\\.zip"

      - name: Extract dependencies.zip
        run: |
          # Find the downloaded zip file
          $zipFile = Get-ChildItem -Path . -Filter 'dependencies.zip' -Recurse
          # Extract the zip file into the root folder
          Expand-Archive -Path $zipFile.FullName -DestinationPath .
          # Remove the zip file
          Remove-Item -Path $zipFile.FullName

      - name: Build Solver.sln
        working-directory: MinesweeperSolver
        run: msbuild.exe Solver.sln
