name: Download Dependencies and Build

on:
  push:
    branches:
      - main  # adjust this to match your main branch name

jobs:
  download_and_build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Download dependencies
        uses: robinraju/release-downloader@v1.9
        with:
            repository: "ZsakaiBalint/MinesweeperSolver"
            latest: true
            fileName: "dependencies.zip"

      - name: Extract dependencies
        run: |
          $filepath = Get-ChildItem -Path 'D:\a\MinesweeperSolver\MinesweeperSolver\' -Filter *.zip -Recurse
          $shell = new-object -com shell.application
          foreach($file in $filepath) {
            $zip = $shell.NameSpace($file.FullName)
            foreach($item in $zip.items()) {
              $shell.Namespace($file.DirectoryName).copyhere($item)
            }
            Remove-Item $file.FullName
          }

      - name: Build Solver.sln
        working-directory: MinesweeperSolver
        run: msbuild.exe Solver.sln
